Controllers
Dinnyeee/Haziorvos pull request #10
Opened 2023-11-19 23:41 UTC by Fekuszka

2023-11-23 17:22 UTC, Zsupi commented on backend/src/main/kotlin/com/dinnye/backend/service/implementation/DoctorServiceImpl.kt
> +        return entity
ez így jó lehet, nekem tetszik

2023-11-23 17:28 UTC, Zsupi requested changes

2023-11-23 17:28 UTC, Zsupi commented on backend/src/main/kotlin/com/dinnye/backend/mapper/InfoDtoMapper.kt
> +    fun map(userPostDto: UserPostDto, @MappingTarget doctor: Doctor)
Ez ne itt legyen, inkább egy UserMapper-be tedd bele. De ott a MappingTarget lehet User, mivel jelenleg arra panaszkodik, hogy a User absztrakt és nem tudja létrehozni. De ha a usert paraméterként adod át akkor már tudja használni.

2023-11-23 17:28 UTC, Zsupi commented on backend/src/main/kotlin/com/dinnye/backend/dto/InfoDtos.kt
>  ) : Serializable
Ezt szedd ki egy külön file-ba mivel ez nem InfoDto.

2023-11-26 22:54 UTC, Zsupi commented on backend/src/main/kotlin/com/dinnye/backend/db/model/User.kt
> +    }
ezeket meg tudod oldani property getter metodussal lehet ra kell rakni meg egy annotaciot h normalisan mukodjon a generalt java kod

2023-11-26 22:55 UTC, Zsupi commented on backend/src/main/kotlin/com/dinnye/backend/db/model/User.kt
> +    var pw: String? = null
így nem fog jól működni a mapstruct

2023-11-26 23:47 UTC, Fadora approved these changes

2023-11-26 23:48 UTC, Fadora approved these changes

2023-11-26 23:49 UTC, merged